[package]
name = "rustat"
version = "0.2.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
time = "0.1.42"
hex = "0.3.2"
glob = "0.2.11"
blocks_iterator = "0.4.0"
env_logger = "0.9.0"
