[package]
name = "rustat"
version = "0.2.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

[dependencies]
chrono = "0.4"
time = "0.1"
serde_json = "1.0.9"
bitcoin = "0.15.1"
hex = "0.3.2"