[package]
name = "rustat"
version = "0.2.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
time = "0.1.42"
bitcoin = "0.15.1"
hex = "0.3.2"
rocksdb = "0.11.0"