[package]
name = "rustat"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]

[dependencies]
chrono = "0.4"
time = "0.1"
handlebars = "0.29.1"
serde_json = "1.0.9"
bitcoin = "0.10"
rustc-serialize = "0.3"
error-chain = "0.11.0"
num_cpus = "1.8.0"