[package]
name = "rustat"
version = "0.2.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
time = "0.1.42"
# bitcoin = "0.18.0"
bitcoin_hashes = "0.7.0"
hex = "0.3.2"
rocksdb = "0.14.0"
glob = "0.2.11"
bitcoin = { git = "https://github.com/rust-bitcoin/rust-bitcoin" }
